// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcrV6NlMgp8dY-i-TC9xeYAtZa1MmP-to',
    appId: '1:964876233360:web:d378dabc4bc5cdc63e0615',
    messagingSenderId: '964876233360',
    projectId: 'ferreteriaestandar',
    authDomain: 'ferreteriaestandar.firebaseapp.com',
    storageBucket: 'ferreteriaestandar.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQHsDkvpoXsyxB6HVgfnsM4CF04evtR58',
    appId: '1:964876233360:android:28c0143c62b53c553e0615',
    messagingSenderId: '964876233360',
    projectId: 'ferreteriaestandar',
    storageBucket: 'ferreteriaestandar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkNnLDt6KiMeAxAyDbXY12DIPQxCyBXsI',
    appId: '1:964876233360:ios:1fd6124a7981cf5c3e0615',
    messagingSenderId: '964876233360',
    projectId: 'ferreteriaestandar',
    storageBucket: 'ferreteriaestandar.appspot.com',
    iosBundleId: 'com.example.motostopsvApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkNnLDt6KiMeAxAyDbXY12DIPQxCyBXsI',
    appId: '1:964876233360:ios:49279bb60ac941813e0615',
    messagingSenderId: '964876233360',
    projectId: 'ferreteriaestandar',
    storageBucket: 'ferreteriaestandar.appspot.com',
    iosBundleId: 'com.example.motostopsvApp.RunnerTests',
  );
}
